### PR TITLE
Fixes #39: Lively updates suggestions

### LINKED ISSUE #39: Tweet search suggestions now showing properly
* Issue Type: Bug Report

### Brief Description
Suggestions only get updated the first time `SuggestFragment` is opened i.e. its `onCreateView` is invoked. If the user goes from `SuggestFragment` to `TweetHarvestingFragment` or `SearchFragment` and navigates back, the suggestions are not getting updated.

### Steps to reproduce
Navigate in the following way:
* TweetHarvestingFragment (app opens) -> SuggestFragment (suggestions updated properly) -> Press back button for navigating back to TweetHarvestingFragment -> Again comeback to SuggestFragment (doesn't update suggestion)
* TweetHarvestingFragment (app opens) -> SuggestFragment (suggestion updated properly) -> click on any suggestion -> SearchFragment -> press back button for navigating back to SuggestFragment (doesn't update suggestions)

### PR DESCRIPTION
**Pull request by SKrPl**
Solves issue: https://github.com/fossasia/loklak_wok_android/issues/39
CompositeDisposable instantiation, network calls and Textwatcher code is shifted to onStart so that returning back from a Fragment updates the suggestions lively.

### CODE REVIEW

**Comment by SKrPl** [comment]
@abishekvashok @Achint08 @djmgit @hemantjadon @kavithaenair @singhpratyush @vibhcool Please review :smile: .

**Review by singhpratyush — APPROVED** [review]
Nice :+1:.

**Review by Achint08 — APPROVED** [review]
LGTM 👍

**Review by djmgit — APPROVED** [review]
Looks good

**Review by kavithaenair — APPROVED** [review]

**Pull request merged**
