### PR TITLE
Fixes #41: Adds tweet posting

### LINKED ISSUE #41: Add Tweet Posting functionality
**Issue type**: Enhancement

The following needs to be completed to solve this issue:
- [x] Post the tweet using public Twitter POST API endpoint.
- [x] Once tweet is successfully posted, use the data to create a JSONObject that matches the format of Loklak's [push](http://loklak.org/api.html#push) API endpoint.
- [x] Media can be attached with a tweet.
- [x] Add location to tweet
- [x] Send the posted tweet to LoklakServer using push API endpoint.

### PR DESCRIPTION
**Pull request by SKrPl**
Fixes issue: https://github.com/fossasia/loklak_wok_android/issues/41

This commit adds the following features:
1. The oauth-signature is generated by modifying the snippet from https://gist.github.com/serj-lotutovici/f85518e99b23008b3180 .
2. 3-legged Authorization, which allows the user to log in to Twitter to authorize Loklak wok to post their tweet.
3. Runtime android permissions for camera, files and location.
4. Tweet posting functionality, with images and location:
    * Images are posted using a multipart post request which returns a mediaId, the API endpoint used is: https://dev.twitter.com/rest/reference/post/media/upload.
    * Location of user is obtained from Location Manager.
    * meidaId and location are passed as parameters to statuses/update twitter API endpoint.
5. Finally the posted tweet is cross posted to loklak server using push API endpoint of loklak_server.

### CODE REVIEW

**Comment by SKrPl** [comment]
@mariobehling @Orbiter @sudheesh001 @daminisatya @Achint08 @djmgit @hemantjadon @kavithaenair @singhpratyush @vibhcool Please review.
Screenshots attached in tweet: https://twitter.com/SKrPl_97/status/889921358653685760

**Comment by SKrPl** [comment]
Test APK link: https://drive.google.com/open?id=0B_L50ue18BeuMUJLcnZQcGlmYjg

**Comment by mariobehling** [comment]
Travis is failing.

Please actively work with your co-developers to finalize this.

**Comment by SKrPl** [comment]
@mariobehling Travis is failing because it doesn't support the latest SDK. Should I revert back to a SDK that is being supported by Travis ?

**Comment by SKrPl** [comment]
Rebased it and reverted back to SDK supported by TravisCI.

**Comment by vibhcool** [comment]
screenshot_2017-07-27-18-38-17-729_com miui bugreport

the app failed when I wrote tweet and clicked on post
platform: android marshmallow
miui 8

**Review by hemantjadon — APPROVED** [review]

**Review by vibhcool — CHANGES_REQUESTED** [review]
please see the comment. there appears to be a bug

**Comment by djmgit** [comment]
@SKrPl resolve conflicts and rebase!

**Comment by SKrPl** [comment]
@vibhcool thanks for pointing the error out. I have solved it, please clear data from of the app in Settings and try logging in again.

@djmgit Resolved merge conflicts and rebased it.

New Test APK link: https://drive.google.com/file/d/0B_L50ue18BeudjVRNWtXXzVEbWM/view?usp=sharing

**Review by singhpratyush — APPROVED** [review]
@SKrPl: The app is working fine. Good job!

But please make smaller PRs and try to introduce features over several commits so that we can make better use of git.

**Comment by vibhcool** [comment]
@SKrPl , does Lokla Wok supports image posting?

**Review by Achint08 — APPROVED** [review]
Working fine even for me. 
Just @singhpratyush said. Smaller PRs.

**Comment by vibhcool** [comment]
I am able to post pic from camera, but not from gallery.

here I posted a pic and wrote text "posted a pic", on clicking post: 

screenshot_2017-07-29-21-26-43-399_org loklak android wok

**Comment by SKrPl** [comment]
@vibhcool that's strange, can you try posting the same image you posted from camera by selecting it from gallery? And please share the image which you were trying to tweet. PS: The image size should not be greater than 3MiB.

**Comment by vibhcool** [comment]
@SkrPl, I tried image with 504kb size which was clicked by camera. Error persists with same screen :P

Also the pic that is directly clicked from app isn't stored in gallery. It is just posted on twitter. Is it normal?

**Comment by vibhcool** [comment]
the image I tried to post:- 
img_20170615_213817

**Comment by SKrPl** [comment]
@vibhcool I tried with the image from both Marshmallow and Nougat (both stock Android) thinking that there may be API incompatibility problem, but that wasn't the case. From both Android M and N, I was able to post the tweet successfully.
Link:
* Only Image from Marshmallow: https://twitter.com/RiteshYadav96/status/892178201979387904
* Image with text from Marshmallow: https://twitter.com/RiteshYadav96/status/892177658984800256
* Image with text from Nougat: https://twitter.com/RiteshYadav96/status/892160824483102721

And also tried to post image around 2-3 MiB, it was successful:
* Only image from Nougat (Image size > 2MiB): https://twitter.com/RiteshYadav96/status/892165266292879360

**Comment by SKrPl** [comment]
@vibhcool We can try one thing! Can you please share the .apk file you have installed, by taking the backup of the app, by using **ES File Explorer** or similar app (just clear the data of the app from settings before taking backup :P ) ? I will install the same .apk and debug it :smile: .

**Comment by vibhcool** [comment]
Link to app, I installed: https://drive.google.com/file/d/0B8N6vCthsU95ekE1bUx4aUlReXM/view?usp=sharing

**Review by vibhcool — APPROVED** [review]
The app is working in other android device(kitkat) as I tested. It is working in other devices you mentioned. So I am approving this. :)
👍

**Pull request merged**
