### PR TITLE
Implemented using api.loklak.org links instead of loklak.org

### PR DESCRIPTION
**Pull request by idealadarsh**
Fixes: https://github.com/fossasia/loklak_wok_android/issues/12

### CODE REVIEW

**Review by abishekvashok — APPROVED** [review]
Nice work

**Comment by mariobehling** [comment]
Thanks! Please also help to resolve merge conflicts.

**Comment by idealadarsh** [comment]
@mariobehling Yes sir! The Travis build is failing because of some error in 'gradlew' file present in the root of this project.

Can we open a new issue for this problem.
Please check the travis CI logs to get more details for creating the issue.

**Comment by idealadarsh** [comment]
I'll solve the merge conflicts.

**Comment by jigyasa-grover** [comment]
Squash the commits into one @adarsh-ideal and we are good to go..

**Comment by mariobehling** [comment]
Thank you!

**Pull request merged**
