### PR TITLE
Fixes #42: Codecov reports displayed using Jacoco

### LINKED ISSUE #42: No coverage reports generated for PRs
Though `.travis.yml` file asks a [push to codecov.io](https://github.com/fossasia/loklak_wok_android/blob/master/.travis.yml#L40), a coverage report is not generated in PRs.

Hint: https://github.com/loklak/loklak_server/pull/1274.

### PR DESCRIPTION
**Pull request by SKrPl**
Solves issue: https://github.com/fossasia/loklak_wok_android/issues/42

### CODE REVIEW

**Comment by SKrPl** [comment]
@Achint08 @djmgit @hemantjadon @kavithaenair @singhpratyush @vibhcool Please review.

**Review by djmgit — APPROVED** [review]
LGTM

**Review by Achint08 — APPROVED** [review]

**Review by singhpratyush — APPROVED** [review]

**Review by kavithaenair — APPROVED** [review]

**Review by vibhcool — APPROVED** [review]

**Comment by abishekvashok** [comment]
^^ failing tests.

**Comment by singhpratyush** [comment]
@abishekvashok: The project coverage check shows an error because no report exists as of now in the project to compare to.

There is nothing wrong with it.

**Comment by abishekvashok** [comment]
Ok then. I didn't had time to look into the tests. Thanks for the explanation. Good work.

**Review by abishekvashok — APPROVED** [review]

**Pull request merged**
