### PR TITLE
Fixes #66: Changes package name

### LINKED ISSUE #66: Change package name and remove old implementations
Make the app ready for alpha release publishing.
- [x] Change package name from `org.loklak.android` to `loklak.wok.android`
- [x] Delete old implementations of Loklak wok and .jar files (present in `app/libs`).
- [x] Change License information in README.md file.

### PR DESCRIPTION
**Pull request by SKrPl**
Changes package name from org.loklak.android to loklak.wok.android and
removes old implementations. The license details in README.md file are
also changed accordingly.

### CODE REVIEW

**Comment by SKrPl** [comment]
@abishekvashok @Achint08 @djmgit @hemantjadon @kavithaenair @singhpratyush @vibhcool Please review.

APK link: https://drive.google.com/open?id=0B_L50ue18BeuTVRTU0Q3MklCQUE

**Review by sudheesh001 — APPROVED** [review]
The changes in refactoring work but I am wondering if it's right to start the package name with `loklak.wok.*` instead of `org.loklak.wok.*` Something about the convention just seems to be pinching me here. @Orbiter can have the final say.

**Comment by mariobehling** [comment]
Yes, org.loklak.wok sounds good. I thought adding org at the beginning is the standard.

**Comment by SKrPl** [comment]
@sudheesh001 @mariobehling Changed package name to `org.loklak.wok`.

**Review by Achint08 — APPROVED** [review]

**Review by vibhcool — APPROVED** [review]

**Pull request merged**
