### PR TITLE
Fixes #53: Adds Fabric crashlytics

### LINKED ISSUE #53: Add crashlytics
**Issue type**: Feature enhancement

### Short Description
Add crashlytics for easy debugging and solving crash issues.

### PR DESCRIPTION
**Pull request by SKrPl**
Fabric crashlytics is added for solving crash issues.

### CODE REVIEW

**Comment by SKrPl** [comment]
@mariobehling @Achint08 @djmgit @hemantjadon @kavithaenair @singhpratyush @vibhcool Please review.

**Review by vibhcool — CHANGES_REQUESTED** [review]
Please fix the error. It is related to API key. Mustn't  API key be uncommented?

**Comment by SKrPl** [comment]
@vibhcool Fixed the build error. API keys can't be shared publicly, doing this would violate terms and conditions. So, I commented out the crashlytics thing, and added `TODO`, so that Android Studio marks it and users who want to use it can comment out the TODOs and user their personal API key.

**Comment by vibhcool** [comment]
@SKrPl,  Instead of commenting in source file. Could you create a config file for the project where API key can reside?

**Comment by SKrPl** [comment]
@vibhcool The API key needs to be provided in the Manifest.xml file and to store the API secret fabric generates `fabric.properties` file analogous to a config file inside `app` directory.

**Review by Achint08 — APPROVED** [review]
LGTM 👍

**Review by djmgit — APPROVED** [review]

**Review by vibhcool — APPROVED** [review]

**Review by kavithaenair — APPROVED** [review]

**Pull request merged**
