### PR TITLE
Cleans up the apk branch

### PR DESCRIPTION
**Pull request by abishekvashok**
The apk branch contained old .apk files of the project which is now
cleaned for regular automatic updates per commit made. They are
now cleaned and new apk files have been added.

Referencing: #9.

### CODE REVIEW

**Comment by mariobehling** [comment]
@abishekvashok Please check about travis.

**Comment by abishekvashok** [comment]
@mariobehling why should we run tests on the `apk` branch, it just stores te apk right? >> #26

**Comment by mariobehling** [comment]
You are right and actually there does not need to be a clean up of the apk branch. The branch should be cleaned up by the script. If there is anything that is not cleaned up by the script yet, then that should be done and the changes need to be made in the master branch. Therefore closing this.

**Comment by abishekvashok** [comment]
The script would update the contents of the `apk` branch with the contents of the build folder (in Travis env). The build folder contains the generated apks in the following format:

./apk_debug.apk
./apk_unaligned.apk

The script will copy these to the cloned repo's apk branch and check if there are any changes. However, the branch currently contains some unwanted apks. So I thought of removing them. I will update the script then to remove the contents of the apk branch on each run. I am creating an issue.

**Pull request closed without merging**
